version: "3.5"

services:
    running:
        build:
            context: ./
            dockerfile: deployments/development.dockerfile
        volumes:
            - .:/code
        entrypoint: ["bash", "scripts/hot-reload-run.sh"]
    testing:
        build:
            context: ./
            dockerfile: deployments/development.dockerfile
        volumes:
            - .:/code
        entrypoint: ["bash", "scripts/hot-reload-tests.sh"]