version: "3.5"

services:
    running:
        image: cryptellation/golang-dev
        volumes:
            - .:/code
        environment: 
            - DIRECTORY=cmd/service
            - BINARY=service
        entrypoint: ["bash", "/scripts/hot-reload-run.sh"]
    unit-tests:
        image: cryptellation/golang-dev
        volumes:
            - .:/code
        entrypoint: ["bash", "/scripts/hot-reload-tests.sh"]